version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - java -version
      - gradle -version
  build:
    commands:
      - ./gradlew clean build
reports:
  arn:aws:codebuild:ap-south-1:916116923608:report-group/code_coverrage:
    files:
      - '**/*'
    base-directory: 'build'
  arn:aws:codebuild:ap-south-1:916116923608:report-group/code_coverrage:
    files:
      - 'build/jacoco_report/test/jacocoTestReport.xml'
    file-format: 'JACOCOXML'  
artifacts:
  files:
    - '**/*'
  name: concurrencysample-$(date +%Y-%m-%d)
