apiVersion: apps/v1
kind: Deployment
metadata:
  name: database1
  labels:
    app: database1
spec:
    replicas: 1
    selector:
      matchLabels:
        app: database1
    template:
      metadata:
        labels:
          app: database1
      spec:
        containers:
        - name: database1
          image: 916116923608.dkr.ecr.ap-south-1.amazonaws.com/database:latest
          ports:
          - containerPort: 3306
---         
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  labels:
    app: backend1
spec:
    replicas: 1
    selector:
      matchLabels:
        app: backend1
    template:
      metadata:
        labels:
          app: backend1
      spec:
        containers:
        - name: backend1
          image: 916116923608.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
          ports:
          - containerPort: 9000
          env:
          - name: APP_DB
            value: laravel
          - name: APP_DB_USER
            value: laravel
          - name: APP_DB_PASS
            value: laravel
          - name: DB_HOST
            value: 10.100.58.212
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1
  labels:
    app: frontend1
spec:
    replicas: 1
    selector:
      matchLabels:
        app: frontend1
    template:
      metadata:
        labels:
          app: frontend1
      spec:
        containers:          
        - name: frontend1
          image: 916116923608.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
          ports:
          - containerPort: 80
          env:
          - name: APP_DB
            value: laravel
          - name: APP_DB_USER
            value: laravel
          - name: APP_DB_PASS
            value: laravel
          - name: DB_HOST
            value: 10.100.58.212
          - name: BACK_HOST
            value: 10.100.63.235
          - name: SERVER_NAME
            value: 10.100.202.230


