apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
    replicas: 1
    selector:
      matchLabels:
        app: backend
    template:
      metadata:
        labels:
          app: backend
      spec:
        containers:
        - name: backend
          image: 916116923608.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
          ports:
          - containerPort: 9000
          env:
          - name: APP_DB
            value: laravel
          - name: APP_DB_USER
            value: laravel
          - name: APP_DB_PASS
            value: laravel
          - name: DB_HOST
            value: 10.100.100.230
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
    selector:
      app: backend
    ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
    type: NodePort