apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
    replicas: 1
    selector:
      matchLabels:
        app: database
    template:
      metadata:
        labels:
          app: database
      spec:
        containers:
        - name: database
          image: 916116923608.dkr.ecr.ap-south-1.amazonaws.com/database:latest
          ports:
          - containerPort: 3306
---         
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
    replicas: 1
    selector:
      matchLabels:
        app: backend
    template:
      metadata:
        labels:
          app: backend
      spec:
        containers:
        - name: backend
          image: 916116923608.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
          ports:
          - containerPort: 9000
          env:
          - name: APP_DB
            value: laravel
          - name: APP_DB_USER
            value: laravel
          - name: APP_DB_PASS
            value: laravel
          - name: DB_HOST
            value: 10.100.255.80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
    replicas: 1
    selector:
      matchLabels:
        app: frontend
    template:
      metadata:
        labels:
          app: frontend
      spec:
        containers:          
        - name: frontend
          image: 916116923608.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
          ports:
          - containerPort: 80
          env:
          - name: APP_DB
            value: laravel
          - name: APP_DB_USER
            value: laravel
          - name: APP_DB_PASS
            value: laravel
          - name: DB_HOST
            value: 10.100.255.80
          - name: BACK_HOST
            value: 10.100.201.166
          - name: SERVER_NAME
            value: 10.100.7.114


